SciChart version 5.0.0.9919
Revision Message
-------- -------
    9820 Some more changes for histobar series
    9821 - fix crash when re eanling pointe marker on water fall
         - allow label for exponential axis to reduce their counts at steep
         angles
    9822 - perfromt the depth offset on water fall stroke in the shader.
         - remove the unneeded unit circle mesh and the method that uses it
    9823 - SC-4000 Fix TextDrawing with flipped YCoordinates in
         NonUniformHeatmap
           --- fixed text drawing;
         - SC-3971 Create NonUniformHeatmap dataseries\renderable series
           --- added HqRenderContext implementation;
           --- added XamlRenderContext implementation;
    9824 - fixed SC-4002 Fix NonUniformHeatmap hittest;
    9825 - fixed SC-3966 Fix UniformHeatmap and PaletteProvider export;
    9826 - fix the grid woreframe
         - when grid is reduced, the vertices were not generated property
         resulting in weird artifacts reported in

         https://abtsoftware.myjetbrains.com/youtrack/issue/SC3D-386
    9827 - use camera angle to change the order of water fall slices to
         render, as they only need one of two orders
         - this solves the transparency issue in SC3D-364
    9828 Some code refactoring for
         FastBottomSideHorizontalHistogramRenderableSeries and for
         FastRightSideVerticalHistogramRenderableSeries
         And also some changes for ITick and CandlestickMetaData
    9829 Some missed changes for histogram bars series
    9830 Added possibility to change max candlesticks with histobars in
         FastHistoBarRenderableSeries
    9832 SC-3881: added AggregationFilter and MovingAverageFilter
    9833 SC-3688 Fixed "50 Channels EEG" example when it doesn't show Fps.
         SC-3767 Fixed and changes toolbar in "Simple Uniform Mesh" example.

    9841 Merged revision(s) 9742-9840 from branches/SciChart_v4.2_Release:
         SC-3958 Fixed the issue with points selection when selection rect
         goes outside the window bounds
         (https://abtsoftware.myjetbrains.com/youtrack/issue/SC-3958)
         ........
         SC-3957 Investigated and fixed when pie/donut charts not resizing
         well issue
         ........
         Fixed pie/donut issue when one segment is 100% the pie disappears
         ........
         SC-3916 Fixed gradient for vertical charts with DirectX renderer
         https://abtsoftware.myjetbrains.com/youtrack/issue/SC-3916
         ........
         SC-3916 Considered custom transformations on brush for gradient fill
         https://abtsoftware.myjetbrains.com/youtrack/issue/SC-3916
         ........
         SC-3917 Improved candlestick series drawing with gradient brushes
         https://abtsoftware.myjetbrains.com/youtrack/issue/SC-3917
         ........
         Ignoring failing tests for XAML gradient brushes for now
         ........
         Attempt to force upgrade / uninstall of old version of scichart when
         installing 4.2.2
         ........
         Updated Installer file
         ........
         SC-3997 Fixed the issue when RolloverModifier doesn't work well on
         synchronized surfaces with different alignment of Y axis
         (https://abtsoftware.myjetbrains.com/youtrack/issue/SC-3997)
         ........
         Fixed the broken tests
         ........
         SC-4001 Performance problem causing stutterring when Fifo Series and
         Legend is used

          - EXPERIMENTAL. Fix for above issue. Requires full testing. Buyer
         beware!
         ........
         Fixes activation integration test
         ........
         First draft of a git commit script to push SciChart Examples Suite to
         Github referencing NuGet
         ........
         SC-4005 Publish SciChart WPF v5 Examples to Github ready for early
         access
         ........
         Updates Git Commit scripts
         ........
         Fixes script error
         ........
         Fixed licensing integration tests
         ........
         Fixed the other test ;)
         ........
         Fixes to SciChart.Wpf.Examples script
         ........
         SciChart.Wpf.Examples script now works! (Branch 4.2)
         ........

    9842 SC-3949 AxisBindings MVVM API
          - creating ForMvvm axis classes
    9843 SC-3983 Added drag event for DragDataPointRadarMod
    9844 Made a lot of changes and fixes for histogram series
    9845 Made some changes and fixes for
         FastBottomSideHorizontalHistogramRenderableSeries
    9846 SC-3789 Heatmap, 3D Surface Mesh color map: Color scale should be
         draggable
          - Fixes bug where XAxis scale cannot be dragged
          - Fixes bug where watermark is shown on axis

    9847 - fixed SC-4003 Implement NonUniform Heatmap for DirectX renderer;
         - fixed text drawing in NonUniformHeatmap using DirectX RenderContext;
    9848 SC-3984 Made visual indicator of closest datapoint for radar tooltip
    9849 Fixes a mess I made
    9850 Some more changes and fixes for histogram series and renamed one prop
         in radar tooltip mod
    9851 Added tick size option to series histogram and made some changes and
         fixes for it
    9852 Some more minor changes for histogram series
    9853 Fixed stroke overlap in histogram series
    9854 Minor changes in FastHistoBarRenderableSeries
    9855 SC-3954 AxisBindings3D MVVM API
          - added necessary classes for binding
    9856 SC-3949 AxisBindings MVVM API
          - added ViewModels, Converter and AxesBinding classes
    9857 SC-3949 AxisBindings MVVM API
          - modified AxisBaseViewModel
    9858 SC-3949 AxisBindings MVVM API
          - added StyleKey dependency property for custom styling.
    9859 SC-3954 AxisBindings3D MVVM API
          - added styles for appropriate bindings with ViewModels.
    9860 SC-3949 AxisBindings MVVM API
          - added styles for axis bindings
    9861 SC-3949 AxisBindings MVVM API
          - added binding for StyleKey Dependency property.
    9862 - fixed: SC-3973 UniformHeatmap fix drawing when IsVerticalChart =
         true;
    9863 Fixed bottom histogram series and also made some other minor changes
    9864 SC-3625 Support Annotations via MVVM natively (like SeriesBinding)
         - Styling issues via StyleKey
    9865 SC-3949 AxisBindings MVVM API
          - fix issues with  updating and Id
    9866 SC-4008 Create example for MVVM features in Examples suite.
         - created an example for SciChart bindings
    9867 SC-3974 Impove UniformHeatmap and PaletteProvider example
    9868 SC-4007, SC-3881: added ability to track more information when data
         series is changed; improved filters updating when data series is
         changed
    9869 - fix the heught egenration loop to generate same shape no matter how
         big the array is
         - the grod mesh now generates a 32.x32 wireframe for grids which are
         large, this gives the general shape but with much less vertices
    9870 - SC-3818 Allow to have Metadata in HeatmapDataSeries;
           - added AppendMetadata() method;
           - added Test for MetaData usage;
    9871 - added metadata parameter to UniformHeatmapDataSeries constructor;
    9873 SC-3968 Added SelectionChanged event to the
         RadarDataPointSelectionModifier and added DragStarted, DragDelta and
         DragCompleted events to RadarDragDataPointModifier
    9874 SC-3954 AxisBindings3D MVVM API
          - minor changes to styling (FontSize set to 8 by default).
    9875 SC-3954 AxisBindings3D MVVM API
          - fixes for StyleKeyProperty
    9876 SC-3949 AxisBindings MVVM API
          - created unit tests for bindings
    9877 - added ability for NonUniformHeatmap to use HeatmapColorPalette
         instead old styled LinearGradientBrush;
         - modified NonUniformHeatmap example to use dragable HeatmapColorMap;
    9878 SC-3949 AxisBindings MVVM API
          - created unit tests for bindings
    9879 - fix for compilation error: ===>
         TestCases\NonUniformHeatmap\NonUniformHeatmap.xaml.cs(29, 38): error
         CS0029: Cannot implicitly convert type
         'System.Windows.Media.LinearGradientBrush' to
         'SciChart.Charting.Visuals.RenderableSeries.HeatmapColorPalette'
    9880 SC-3954 AxisBindings3D MVVM API
          - fixes minor issue
    9881 SC-3881: added tests for DiscontinuousDataSeries, AggregationFilter;
         made refactoring in filters
    9882 SC-4008 Create example for MVVM features in Examples suite.
         - rename an example from "SciChart Bindings"  to  "Axis Binding and
         Annotation Binding"
    9883 SC-3881: fixed compilation error for previous commit
    9884 SC-3881: fixed compilation error for previous commit
    9885 SC-4008 Create example for MVVM features in Examples suite.
         - fixing  commit issue
    9886 - refactored FastUniformHeatmap data\renderable-serieses drawing when
         IsVerticalChart = true;
    9887 Fixed right side histogram series
    9888 Refactoring:
           - Placed FFT2 class in ExternalDependencies for sharing purpose.
    9889 Refactoring:
           - Renew namespace for FFT2 class where was needed.
    9890 Refactoring:
           - removed unnecessary FFT files
    9891 - refactored UniformHeatmap;
           - chanded zValues array from double[,] to TZ[,] where TZ is
         IComparable;
           - changed ToDouble convertion to use Math instead of
         IComparableExtensions.ToDouble();

    9893 Merged revision(s) 9849-9892 from branches/SciChart_v4.2_Release:
         Fixes a mess I made
         ........
         - fixed bug for support ticket: RII-227-21464
         ........
         Fixes two reported issues with documentation

          1.) Dynamically adjusting TextFormatting code bug
          2.) CustomRenderableSeries code sample bug
         ........

    9894 SC-3769 Blinking Textures from CustomPointMarker
    9895 Minor fix for histogram bar series
    9900 fixing issue with NullReference exception when RenderableSeries is
         getting via SeriesBinding
    9901 Added 2 examples for 3D Bindings
          - for Axis3D bindings
          - for Series3D bindings
    9902 fixing broken build
    9903 SC-3954 AxisBindings3D MVVM API:
         - temporary commented WaterfallRenderableSeries
         - minor changes for AxisBinding example
    9904 SC-3954 AxisBindings3D MVVM API:
         - added test for axis bindings.
    9905 SC-3954 AxisBindings3D MVVM API:
         - added interface for Axis3DViewModel
    9906 SC-3954 AxisBindings3D MVVM API:
         - minor changes for testing purpose
    9914 SC-3818 Allow to have Metadata in HeatmapDataSeries
          - refactored UniformHeatmap and NonUniformHeatmap DataSerieses;
          - added ability to store Metadata for NonUniformHeatmap;
    9915 - modified UniformHeatmap metadataTest
    9917 SC-3956 SciChart Source does not compiler with .NET 4.5 or above
         SC-4020 SharpDX.Direct3D11.Effects requires D3DCompiler_43.dll and
         not found on Win10 pcs

         -- Merged revision(s) 9896-9916 from
         branches/SciChart_v5.0_Release-SharpDX3:

         Fixes blank / hanging examples app after upgrade to SharpDX v3.1.1.
         This required installing-package SharpDX.Mathematics to
         SciChart.Examples.Demo

         Updated usage of Direct3D10RenderSurface -> Direct3D11RenderSurface
         throughout
         ----
         Updates to deploy scripts
         ----
         fixes deploy script
         ----
         Some build error fixes in tests
         ----
         fix bit resources creation
         - all example sould be working with sharpdx 3 now
         ----
         Adds missing dlls
         ----
         Should fix crash of DLL not found
         ----
         allow code to byuld with sharp dx 3
         - we have arun time issue when shaders are Created
         {"Unable to load DLL 'sharpdx_direct3d11_1_effects_x64.dll': The
         specified module could not be found. (Exception from HRESULT:
         0x8007007E)"}
         ----
         Removes net40 from the build scripts
         ----
         Added depdencency SharpDX.Direct3D11.Effects to SciChart.Demo
         ----
         Upgraded all SciChart projects to .NET4.5
         Prereuisite to upgrading to SharpDX v3.1.1
         Updated SciChart.Drawing.DirectX to SharpDX v3.1.1
         Three build errors related to SharpDX (Shady to fix)
         ----

    9918 SC-3881: added base class for filters, updated existed filters and
         tests
    9919 Changes for histogram series